---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: external-node-exporter
  labels:
    app: external-node-exporter
spec:
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
  selector:
    matchLabels:
      app: external-node-exporter
  namespaceSelector:
    matchNames:
      - edu25
---
apiVersion: v1
kind: Service
metadata:
  name: external-node-exporter
  labels:
    app: external-node-exporter
spec:
  ports:
    - name: metrics
      port: 9100
      protocol: TCP
      targetPort: 9100
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-node-exporter
subsets:
  - addresses:
    - ip: 211.251.238.182
    ports:
      - name: metrics
        port: 9100
        protocol: TCP